seed = 0
parent_dir = "privacy_result/bike/syntabrl_best_ML"
real_data_path = "data/bike/"
model_type = "mlp"
num_numerical_features = 5
device = "cuda:0"

[model_params]
is_y_cond = false
d_in = 11
num_classes = 0

[model_params.rtdl_params]
d_layers = [
    256,
    1024,
    1024,
    1024,
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.0004856603584605993
weight_decay = 0.0
batch_size = 4096
evaluation_file = "SynTabRL_eval.json"
pretrain_steps = 4000
privacy_discount = 0.01
logsumexp_sigma = 0.01

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 22244
batch_size = 10000
seed = 4

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[privacy_config]
dcr = 0.2
nndr = 0.85
gower = 0.1
